import random
import pyautogui as pg
import time
animal = ('monkey', 'donkey', 'dog')
time.sleep(8)
for i in rangeYou are a monkey
You are a dog
You are a monkey
You are a donkey
Y1000You are a dog
               You are a dog
               You are a donkey
               You are a dogYou are a DocCGIXMLRPCRequestHandlerYou are a donkey
               You are a monkey
               You are a monkey
               You are a don.keys()You are a dog
               You are a donkey
               You are a dog
               You are a DocCGIXMLRPCRequestHandlerYou are a DeprecationWarningYou are a dog
               You are a donkeyYou are a donkey
               You are a donkey
               You are a donkeyou are a monkey
               You are a monkey
               
               You are a DocCGIXMLRPCRequestHandlerYou are a DeprecationWarningYou are a DocCGIXMLRPCRequestHandler):
    a = random.choice(animal)
    You are a don.keys()You are a don.keys()You are a DocCGIXMLRPCRequestHandlerYou are a DocCGIXMLRPCRequestHandlerYou are a don.keys()You are a mon.keys()You are a don.keys()You are a DocCGIXMLRPCRequestHandlerYou are a DocCGIXMLRPCRequestHandlerYou are a don.keys()You are a monkey
    You are a donkey
    You are a dog
    You are a monkey
    You are a mon.keys()You are a monkey
    You are a mon.keys()
    pg.write("You are a " +a)
    pg.press('enter')