# Generated by Django 4.1.1 on 2023-01-03 06:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.JSONField(default=dict)),
                ('location', models.JSONField(default=dict)),
                ('experience', models.JSONField(default=dict)),
                ('company', models.JSONField(default=dict)),
                ('designation', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=25)),
                ('UserName', models.CharField(max_length=25)),
                ('Email', models.CharField(blank='', max_length=50)),
                ('MobileNumber', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(blank='', max_length=50)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Credits', models.IntegerField(default=0)),
                ('Password', models.CharField(default=app.models.password, max_length=15)),
                ('otp', models.CharField(default=app.models.otp, max_length=10)),
                ('Role', models.CharField(default='', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=app.models.otp, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
