# Generated by Django 4.1.1 on 2023-01-03 06:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_files_recruiter_user_role_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=25)),
                ('UserName', models.CharField(max_length=25)),
                ('Email', models.CharField(blank='', max_length=50)),
                ('MobileNumber', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(blank='', max_length=50)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Credits', models.IntegerField(default=0)),
                ('Password', models.CharField(default=app.models.password, max_length=15)),
                ('otp', models.CharField(default=app.models.otp, max_length=10)),
                ('Role', models.CharField(default='', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
