# Generated by Django 4.1.1 on 2023-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recruiters_delete_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
