# Generated by Django 4.1.1 on 2023-01-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.JSONField(default=dict),
        ),
    ]
