# Generated by Django 4.1.1 on 2023-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
