# Generated by Django 4.1.1 on 2023-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='Role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
