# Generated by Django 4.1.1 on 2023-01-06 06:50

from django.db import migrations, models
# import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_files_alter_recruiters_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='photo',
            field=models.CharField(blank=True),
        ),
    ]
