# Generated by Django 4.1.1 on 2023-01-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fileupload_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='photo',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(default='', editable=False, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='company',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='designation',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='experience',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
    ]
