# Generated by Django 4.1.1 on 2023-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_fileupload_photo_fileupload_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='company',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='designation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='experience',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
