# Generated by Django 4.1.5 on 2023-01-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_fileupload_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='Email',
            field=models.CharField(blank='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(blank='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
