# Generated by Django 4.1.5 on 2023-01-22 19:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_recruiters_email_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbail of the uploaded image'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=app.models.scramble_uploaded_filename),
        ),
    ]
