# Generated by Django 4.1.5 on 2023-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fileupload_thumbnail_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
