# Generated by Django 4.1.5 on 2023-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_fileupload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='designation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='location',
            field=models.TextField(),
        ),
    ]
