# Generated by Django 4.1.5 on 2023-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_fileupload_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
