# Generated by Django 4.1.5 on 2023-01-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
