# Generated by Django 4.1.5 on 2023-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Taqs', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=25)),
                ('Question', models.TextField()),
            ],
        ),
    ]
