# Generated by Django 4.1.5 on 2023-02-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_taqs_assessment_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Features', models.CharField(max_length=100)),
            ],
        ),
    ]
