# Generated by Django 4.1.6 on 2023-03-01 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiters',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 12, 35, 50, 174305)),
        ),
    ]
