# Generated by Django 4.1.6 on 2023-03-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_recruiters_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiters',
            name='created_on',
        ),
        migrations.AddField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 57, 53, 714673)),
        ),
    ]
